include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
  
  errors:
    # Hacer que ciertos warnings sean errores
    invalid_annotation_target: ignore
    todo: ignore
    
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:

  rules:
  # Estilo y legibilidad
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_new
    
    # Evitar errores comunes
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_web_libraries_in_flutter
    - no_logic_in_create_state
    - prefer_void_to_null
    
    # Documentación
    - public_member_api_docs # Comentar si no quieres documentar todo
    
    # Performance
    - avoid_function_literals_in_foreach_calls
    - prefer_foreach
    
    # Seguridad
    - always_use_package_imports
    - avoid_relative_lib_imports
    
    # Organización
    - directives_ordering
    - sort_child_properties_last
    
    # Null safety
    - unnecessary_null_checks
    - unnecessary_nullable_for_final_variable_declarations

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
